version: '3'

services:

  postgres-hospital-go:
    image: 'postgres:16.0'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hospital
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-internal:/var/lib/postgresql/internal
